# Generated by Django 4.2 on 2023-05-31 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='mahasiswaModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nim', models.CharField(max_length=50)),
                ('Nama', models.CharField(max_length=50)),
                ('Kelamin', models.CharField(max_length=50)),
                ('Alamat', models.CharField(max_length=50)),
            ],
        ),
    ]
